kind: pipeline
type: vm
name: default

pool:
  use: ubuntu

steps:
- name: theme
  image: alpine/git
  commands:
  - git clone https://github.com/drone/drone-hugo-theme.git themes/drone-hugo-theme

- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.55.6
    config: config.yaml

- name: publish
  image: lucap/drone-netlify
  settings:
    path: ./public
    site_id:
      from_secret: netlify_site_id
    token:
      from_secret: netlify_token
  when:
    event:
      exclude:
        - pull_request
